import tempfile

import pytest

from open_ost2pst.pst.messaging import MessagingBuilder
from tests._libpff_helpers import get_child_by_name, get_ipm_subtree


pypff = pytest.importorskip("pypff")


def test_libpff_reads_generated_folder_and_message() -> None:
    builder = MessagingBuilder(
        store_name="Open OST2PST Store",
        root_name="Top of Personal Folders",
    )
    inbox = builder.add_folder(builder.root, "Inbox")
    expected = builder.add_message(
        inbox,
        subject="Hello from open-ost2pst",
        body="This message was generated by our PST writer.",
        sender_name="Alice Example",
        sender_email="alice@example.com",
        display_to="Bob Example",
        is_read=True,
    )

    result = builder.build()

    with tempfile.NamedTemporaryFile(suffix=".pst") as handle:
        handle.write(result.data)
        handle.flush()

        store = pypff.file()
        store.open(handle.name)
        try:
            root = get_ipm_subtree(store)
            assert root.get_name() == "Top of Personal Folders"

            inbox_item = get_child_by_name(root, "Inbox")
            assert inbox_item is not None
            assert inbox_item.get_name() == "Inbox"
            assert inbox_item.get_number_of_sub_messages() == 1

            message = inbox_item.get_sub_message(0)
            assert message is not None
            assert message.get_identifier() == expected.nid
            assert message.get_subject() == "Hello from open-ost2pst"
            assert message.get_sender_name() == "Alice Example"
            assert message.get_plain_text_body() == (
                b"This message was generated by our PST writer."
            )
        finally:
            store.close()


@pytest.mark.parametrize("message_count", [447, 448, 1000, 5000])
def test_libpff_reads_large_contents_table(message_count, tmp_path) -> None:
    builder = MessagingBuilder(
        store_name="Open OST2PST Store",
        root_name="Top of Personal Folders",
    )
    inbox = builder.add_folder(builder.root, "Large Inbox")

    for index in range(message_count):
        builder.add_message(
            inbox,
            subject=f"Message {index:05d}",
            body="x",
            internet_message_id=f"<large-{index}@example.invalid>",
        )

    path = tmp_path / f"large-{message_count}.pst"
    builder.write(path)

    store = pypff.file()
    store.open(str(path))
    try:
        root = get_ipm_subtree(store)
        inbox_item = get_child_by_name(root, "Large Inbox")
        assert inbox_item is not None
        assert inbox_item.get_number_of_sub_messages() == message_count

        first = inbox_item.get_sub_message(0)
        last = inbox_item.get_sub_message(message_count - 1)
        assert first is not None
        assert last is not None
        assert first.get_subject() == "Message 00000"
        assert last.get_subject() == f"Message {message_count - 1:05d}"
    finally:
        store.close()
