import tempfile

import pytest

from open_ost2pst.pst.messaging import MessagingBuilder
from tests._libpff_helpers import get_child_by_name, get_ipm_subtree


pypff = pytest.importorskip("pypff")


def test_libpff_reads_generated_folder_and_message() -> None:
    builder = MessagingBuilder(
        store_name="Open OST2PST Store",
        root_name="Top of Personal Folders",
    )
    inbox = builder.add_folder(builder.root, "Inbox")
    expected = builder.add_message(
        inbox,
        subject="Hello from open-ost2pst",
        body="This message was generated by our PST writer.",
        sender_name="Alice Example",
        sender_email="alice@example.com",
        display_to="Bob Example",
        is_read=True,
    )

    result = builder.build()

    with tempfile.NamedTemporaryFile(suffix=".pst") as handle:
        handle.write(result.data)
        handle.flush()

        store = pypff.file()
        store.open(handle.name)
        try:
            root = get_ipm_subtree(store)
            assert root.get_name() == "Top of Personal Folders"

            inbox_item = get_child_by_name(root, "Inbox")
            assert inbox_item is not None
            assert inbox_item.get_name() == "Inbox"
            assert inbox_item.get_number_of_sub_messages() == 1

            message = inbox_item.get_sub_message(0)
            assert message is not None
            assert message.get_identifier() == expected.nid
            assert message.get_subject() == "Hello from open-ost2pst"
            assert message.get_sender_name() == "Alice Example"
            assert message.get_plain_text_body() == (
                b"This message was generated by our PST writer."
            )
        finally:
            store.close()
